---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: moving-people-safely
  namespace: moving-people-safely-prod
spec:
  secretName: mps-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'personescortrecord.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'personescortrecord.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
