kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: serviceaccount-admin
  namespace: laa-apply-for-legalaid-redcjump
subjects:
  - kind: ServiceAccount
    name: default
    namespace: laa-apply-for-legalaid-redcjump
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
