---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: licences-preprod.prison.service.justice.gov.uk
  namespace: licences-preprod
spec:
  secretName: licences-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'licences-preprod.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'licences-preprod.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
