---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: licences.prison.service.justice.gov.uk
  namespace: licences-prod
spec:
  secretName: licences-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'licences.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'licences.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: probation-teams.prison.service.justice.gov.uk
  namespace: licences-prod
spec:
  secretName: probation-teams-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'probation-teams.prison.service.justice.gov.uk'
  acme:
    config:
      - domains:
          - 'probation-teams.prison.service.justice.gov.uk'
        dns01:
          provider: route53-cloud-platform
