kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pathfinder-prod-admin
  namespace: pathfinder-prod
subjects:
  - kind: Group
    name: "github:dps-production-releases"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: pathfinder-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci 
  namespace: pathfinder-prod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: pathfinder-prod
subjects:
- kind: ServiceAccount
  name: tiller
- kind: ServiceAccount
  name: circleci
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
