---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api.pathfinder.service.justice.gov.uk
  namespace: pathfinder-prod
spec:
  secretName: pathfinder-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'api.pathfinder.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'api.pathfinder.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
