---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: offender-search-prod-admin
  namespace: offender-search-prod
subjects:
  - kind: Group
    name: "github:dps-shared"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
