---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: categorisation-tool-prod-admin
  namespace: categorisation-tool-prod
subjects:
  - kind: Group
    name: "github:dps-production-releases"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
