---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: categorisation-tool-prod

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: categorisation-tool-prod
rules:
  - apiGroups:
      - ""
      - "batch"
      - "extensions"
      - "apps"
    resources:
      - "*"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: categorisation-tool-prod
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: categorisation-tool-prod
roleRef:
  kind: Role
  name: tiller
  apiGroup: rbac.authorization.k8s.io
