apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: crime-portal-mirror-gateway-probation.service.justice.gov.uk
  namespace: crime-portal-mirror-gateway-prod
spec:
  secretName: crime-portal-mirror-gateway-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - crime-portal-mirror-gateway-probation.service.justice.gov.uk