apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: laa-apply-for-legalaid-uat
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container
