kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: learning-cloud-deployments-dev-admin
  namespace: learning-cloud-deployments-dev
subjects:
  - kind: Group
    name: "github:minstryofjustice"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
