apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: api.manage-soc-cases-dev.service.justice.gov.uk
  namespace: manage-soc-cases-dev
spec:
  secretName: manage-soc-cases-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - api.manage-soc-cases-dev.service.justice.gov.uk
