apiVersion: v1
kind: Namespace
metadata:
  name: rds-test
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "rds-test"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "cp"
    cloud-platform.justice.gov.uk/application: "rds-test"
    cloud-platform.justice.gov.uk/owner: "cp: cp@justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "cp"
