kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rds-test-admin
  namespace: rds-test
subjects:
  - kind: Group
    name: "github:cp"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
