apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-api
  namespace: <%= @namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: ministryofjustice/cloud-platform-multi-container-demo-app:content-api-1.3
        ports:
        - containerPort: 4567
