---
kind: Service
apiVersion: v1
metadata:
  name: multi-container-demo-postgres
  namespace: <%= @namespace %>
spec:
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
