apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
  namespace: <%= @namespace %>
  labels:
    app: rails-app-service
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: rails-app
