apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails-app
  namespace: <%= @namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: ministryofjustice/cloud-platform-multi-container-demo-app:rails-app-1.3
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: postgres://dummy:dummy@multi-container-demo-postgres.<%= @namespace %>.svc.cluster.local:5432/multi_container_demo_app
          - name: CONTENT_API_URL
            value: "http://content-api-service:4567/image_url.json"
