apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: prison-visits-booking-production
spec:
  limits:
  - default:
      cpu: 250m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 500Mi
    type: Container
