kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: david-add-django-basic-auth-test-admin
  namespace: david-add-django-basic-auth-test
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
