apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: hmpps-submit-information-report-dev.service.justice.gov.uk
  namespace: hmpps-submit-information-report-dev
spec:
  secretName: hmpps-submit-information-report-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - hmpps-submit-information-report-dev.service.justice.gov.uk
