apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-rubyapp
  namespace: <%= @namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-rubyapp
    spec:
      containers:
      - name: rubyapp
        image: ministryofjustice/cloud-platform-helloworld-ruby:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4568
