apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: offender-events-prod
  name: dps-prometheus-rules-sqs
  namespace: offender-events-prod
spec:
  groups:
  - name: DPS-SQS
    rules:
    - alert: SQS-oldest-message
      annotations:
        message: SQS - {{ $labels.queue_name }} has message older than 15mins, check consumers are healthly.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/dps-aws-sqs?orgId=1&from=now-6h&to=now&var-env=prod&var-queue_name={{ $labels.queue_name }}
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1514766438/DPS+CloudPlatform+Apps 
      expr: |-
        sum(aws_sqs_approximate_age_of_oldest_message_maximum{queue_name=~"Digital-Prison-Services-prod.*", queue_name!~".*_dl"} offset 15m) by (queue_name) > 15 * 60
      for: 1m
      labels:
        severity: digital-prison-service
    - alert: SQS-number-of-messages
      annotations:
        message: SQS - {{ $labels.queue_name }} - number of messages={{ $value }} (exceeds 100), check consumers are healthly.  https://grafana.cloud-platform.service.justice.gov.uk/d/AWSSQS000/dps-aws-sqs?orgId=1&from=now-6h&to=now&var-env=prod&var-queue_name={{ $labels.queue_name }}
        runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1514766438/DPS+CloudPlatform+Apps
      expr: |-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"Digital-Prison-Services-prod.*", queue_name!~".*_dl"} offset 15m) by (queue_name) > 100
      for: 1m
      labels:
        severity: digital-prison-service
