apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: jason-lab
spec:
  limits:
  - default:
      cpu: 250m
      memory: 500Mi
    defaultRequest:
      cpu: 16m
      memory: 150Mi
    type: Container
