---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: offender-events-preprod.prison.service.justice.gov.uk
  namespace: offender-events-preprod
spec:
  secretName: offender-events-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'offender-events-preprod.prison.service.justice.gov.uk'
  acme:
    config:
      - domains:
          - 'offender-events-preprod.prison.service.justice.gov.uk'
        dns01:
          provider: route53-cloud-platform
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: offender-events-preprod.prison.service.justice.gov.uk
  namespace: offender-events-preprod
spec:
  secretName: offender-events-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'offender-events-preprod.prison.service.justice.gov.uk'
  acme:
    config:
      - domains:
          - 'offender-events-preprod.prison.service.justice.gov.uk'
        dns01:
          provider: route53-cloud-platform
