kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-app-admin
  namespace: demo-app
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: demo-app

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: demo-app
rules:
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: demo-app
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: demo-app
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io