---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-production
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "dev"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "moj-digital"
    cloud-platform.justice.gov.uk/application: "helloworld"
    cloud-platform.justice.gov.uk/owner: "jason: digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app"
---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse-webops
  labels:
    cloud-platform.justice.gov.uk/is-production: "true"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "moj-digital"
    cloud-platform.justice.gov.uk/owner: "jason: digital.justice.gov.uk"
