---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: keyworker-api-dev.prison.service.justice.gov.uk
  namespace: keyworker-api-dev
spec:
  secretName: keyworker-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'keyworker-api-dev.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'keyworker-api-dev.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
