apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: ${namespace}
spec:
  limits:
  - default:
      cpu: 50m
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
