apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: ${namespace}
spec:
  limits:
  - default:
      cpu: 250m
      memory: 500Mi
    defaultRequest:
      cpu: 12m
      memory: 150Mi
    type: Container
