apiVersion: v1
kind: Namespace
metadata:
  name: gitops-test
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "dev"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "webops"
    cloud-platform.justice.gov.uk/application: "webops"
    cloud-platform.justice.gov.uk/owner: "jason: jason"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app"
---
apiVersion: v1
kind: Namespace
metadata:
  name: concourse-webops
