kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nomis-api-access-staging-admin
  namespace: nomis-api-access-staging
subjects:
  - kind: Group
    name: "github:omic"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
