---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: prison-data-compliance-dev

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: prison-data-compliance-dev
rules:
  - apiGroups:
      - ""
      - "batch"
      - "extensions"
      - "apps"
    resources:
      - "*"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: prison-data-compliance-dev
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: prison-data-compliance-dev
roleRef:
  kind: Role
  name: tiller
  apiGroup: rbac.authorization.k8s.io
