---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: checkmydiary.service.justice.gov.uk
  namespace: check-my-diary-prod
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'checkmydiary.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'checkmydiary.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
