---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmpps-socu-dev-admin
  namespace: hmpps-socu-dev
subjects:
  - kind: Group
    name: "github:dps-pathfinder-tech"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
