apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: dev.hmpps-socu.service.justice.gov.uk
  namespace: hmpps-socu-dev
spec:
  secretName: hmpps-socu-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - dev.hmpps-socu.service.justice.gov.uk
