kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laa-court-data-adaptor-test-admin
  namespace: laa-court-data-adaptor-test
subjects:
  - kind: Group
    name: "github:laa-crime-apps-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: laa-court-data-adaptor-test
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: laa-court-data-adaptor-test
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: laa-court-data-adaptor-test
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
