apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: laa-court-data-adaptor-test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: laa-court-data-adaptor-test
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "jobs"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: laa-court-data-adaptor-test
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: laa-court-data-adaptor-test
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
