apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: categorisation-tool-preprod
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: categorisation-tool-preprod-admin
  namespace: categorisation-tool-preprod
subjects:
  - kind: Group
    name: "github:omic"
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: circleci
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
