apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: tls-wildcard
  namespace: formbuilder-services-pentest-dev
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - '*.dev.test.form.service.justice.gov.uk'
