---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dev.moving-people-safely.service.justice.gov.uk
  namespace: moving-people-safely-dev
spec:
  secretName: moving-people-safely-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'dev.moving-people-safely.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'dev.moving-people-safely.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
