kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: formbuilder-submit-product-production-admin
  namespace: formbuilder-submit-product-production
subjects:
  - kind: Group
    name: "github:form-builder"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
