apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci-formbuilder-submit-product-production
  namespace: formbuilder-submit-product-production
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci-formbuilder-submit-product-production
  namespace: formbuilder-submit-product-production
subjects:
- kind: ServiceAccount
  name: circleci-formbuilder-submit-product-production
  namespace: formbuilder-submit-product-production
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
