kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: probation-core-services-tooling-test-admin
  namespace: probation-core-services-tooling-test
subjects:
  - kind: Group
    name: "github:hmpps-core-services"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
