---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: development.sentence-planning.service.justice.gov.uk
  namespace: sentence-planning-development
spec:
  secretName: sentence-planning-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'development.sentence-planning.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'development.sentence-planning.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform