---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: probation-core-services-tooling

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: probation-core-services-tooling
rules:
  - apiGroups:
      - ""
      - "batch"
      - "extensions"
      - "apps"
      - "rbac.authorization.k8s.io"
      - "monitoring.coreos.com"
    resources:
      - "*"
    verbs:
      - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: probation-core-services-tooling
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: probation-core-services-tooling
roleRef:
  kind: Role
  name: tiller
  apiGroup: rbac.authorization.k8s.io
