---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: probation-core-services-tooling

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: probation-core-services-tooling
subjects:
  - kind: ServiceAccount
    name: circleci
    namespace: probation-core-services-tooling
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
