apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: dstest-devd
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
