apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: contact-moj-development-certificate
  namespace: contact-moj-development
spec:
  secretName: contact-moj-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'development.contact-moj.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'development.contact-moj.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
