---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: whereabouts-dev.prison.service.justice.gov.uk
  namespace: digital-prison-services-dev
spec:
  secretName: prison-staff-hub-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'whereabouts-dev.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'whereabouts-dev.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: digital-dev.prison.service.justice.gov.uk
  namespace: digital-prison-services-dev
spec:
  secretName: notm-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'digital-dev.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'digital-dev.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
