apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: prison-visits-booking-staging
spec:
  limits:
  - default:
      cpu: 100m
      memory: 1000Mi
    defaultRequest:
      cpu: 50m
      memory: 500Mi
    type: Container
