apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: disclosure-checker-certificate-production
  namespace: disclosure-checker-production
spec:
  secretName: disclosure-checker-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'check-when-to-disclose-cautions-convictions.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'check-when-to-disclose-cautions-convictions.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
