apiVersion: v1
kind: Namespace
metadata:
  name: claim-criminal-injuries-compensation-stg
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "claim-criminal-injuries-compensation-stg"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "cica"
    cloud-platform.justice.gov.uk/application: "data-capture-service"
    cloud-platform.justice.gov.uk/owner: "cica: infrastructure@cica.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials?ref=3.2"
