kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: parliamentary-questions-dev-admin
  namespace: parliamentary-questions-dev
subjects:
  - kind: Group
    name: "github:parliamentary-questions"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
