apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: logging
spec:
  limits:
  - default:
      cpu: 100m
      memory: 500Mi
    defaultRequest:
      cpu: 10m
      memory: 400Mi
    type: Container
