apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: peoplefinder-production-certificate
  namespace: peoplefinder-production
spec:
  secretName: peoplefinder-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'peoplefinder.service.gov.uk'
  acme:
    config:
    - domains:
      - 'peoplefinder.service.gov.uk'
      dns01:
        provider: route53-cloud-platform
