kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hmcts-mock-api-dev-admin
  namespace: hmcts-mock-api-dev
subjects:
  - kind: Group
    name: "github:laa-crime-apps-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: hmcts-mock-api-dev
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: hmcts-mock-api-dev
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: hmcts-mock-api-dev
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
