apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: hmcts-mock-api-dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: hmcts-mock-api-dev
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources:
      - "pods/portforward"
      - "deployment"
      - "secrets"
      - "services"
      - "pods"
      - "jobs"
    verbs:
      - "patch"
      - "get"
      - "create"
      - "delete"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
      - "ingresses"
    verbs:
      - "get"
      - "update"
      - "delete"
      - "create"
      - "patch"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: hmcts-mock-api-dev
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: hmcts-mock-api-dev
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
