kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: matt-demo-admin
  namespace: matt-demo
subjects:
  - kind: Group
    name: "github:ministryofjustice/tactical-products"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
