kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: matt-demo-admin
  namespace: matt-demo
subjects:
  - kind: Group
    name: "github:tactical-products"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: matt-demo
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: matt-demo
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: matt-demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

