apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: moving-people-safely-preprod

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: moving-people-safely-preprod
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: moving-people-safely-preprod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
