---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: moving-people-safely-preprod
  namespace: moving-people-safely-preprod
spec:
  secretName: moving-people-safely-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'moving-people-safely-preprod.prison.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'moving-people-safely-preprod.prison.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
