apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: offender-search-dev.prison.service.justice.gov.uk
  namespace: offender-search-dev
spec:
  secretName: offender-search-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'offender-search-dev.prison.service.justice.gov.uk'
  acme:
    config:
      - domains:
          - 'offender-search-dev.prison.service.justice.gov.uk'
        dns01:
          provider: route53-cloud-platform

