---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: sign-in-stage
  namespace: prison-api-certificates
spec:
  secretName: sign-in-stage
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - sign-in-stage.hmpps.service.justice.gov.uk
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: sign-in-dev
  namespace: prison-api-certificates
spec:
  secretName: sign-in-dev
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - sign-in-dev.hmpps.service.justice.gov.uk

