apiVersion: v1
kind: Namespace
metadata:
  name: pq-staging
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "staging"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "Parliamentary Questions"
    cloud-platform.justice.gov.uk/application: "Parliamentary Questions Tracker"
    cloud-platform.justice.gov.uk/owner: "Parliamentary Questions: pq@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/parliamentary-questions"
