kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pq-staging-admin
  namespace: pq-staging
subjects:
  - kind: Group
    name: "github:pq-team"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
