apiVersion: v1
kind: Namespace
metadata:
  name: categorisation-tool-preprod
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "preprod"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "HMPPS"
    cloud-platform.justice.gov.uk/application: "categorisation-tool"
    cloud-platform.justice.gov.uk/owner: "Digital Prison Services: michael.willis@digtal.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "https://github.com/ministryofjustice/categorisation-tool.git"
