---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: categorisation-tool-preprod-admin
  namespace: categorisation-tool-preprod
subjects:
  - kind: Group
    name: "github:dps-shared"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
