apiVersion: v1
kind: Namespace
metadata:
  name: checklist
  labels:
    cloud-platform.justice.gov.uk/is-production: "false"
    cloud-platform.justice.gov.uk/environment-name: "production"
  annotations:
    cloud-platform.justice.gov.uk/business-unit: "cp"
    cloud-platform.justice.gov.uk/application: "checklist"
    cloud-platform.justice.gov.uk/owner: "cp: oliver.anwyll@digital.justice.gov.uk"
    cloud-platform.justice.gov.uk/source-code: "github.com"
