# This service account will be used to impersonate user privileges
# and deploy user applications in a Gitops pipeline.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-deploy
  namespace: ${namespace}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-deploy
  namespace: ${namespace}
subjects:
- kind: ServiceAccount
  name: gitops-deploy
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
