kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: common-platform-connector-dev-admin
  namespace: common-platform-connector-dev
subjects:
  - kind: Group
    name: "github:laa-apply-for-legal-aid"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
