---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: parliamentary-questions
  namespace: parliamentary-questions-development
spec:
  secretName: parliamentary-questions-development-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'development.trackparliamentaryquestions.service.gov.uk'
  acme:
    config:
    - domains:
      - 'development.trackparliamentaryquestions.service.gov.uk'
      dns01:
        provider: route53-cloud-platform
